require("general")
require("mappings")
require("plugins")

require("config/autosave")
require("config/compe")
require("config/gitsigns")
require("config/lspconfig")
require("config/lualine")
require("config/neoterm")
require("config/nvim-autopairs")
require("config/nvim-tree")
require("config/telescope")
require("config/tree-sitter")
require("config/trouble")

vim.cmd("colorscheme dracula")
